# Generated by Django 3.0.4 on 2020-03-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deaths', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('confirmed', models.IntegerField(default=0)),
            ],
        ),
    ]
